dist: bionic
language: node_js

# Support Active LTS versions of Node.js
node_js:
  - '10'
  - '12'

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  # Use latest supported NPM in order to speedup build and support `npm ci`
  - npm i -g npm@6

install:
  - npm ci
  
before_deploy:
  # Login to NPM registry
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/travis-deploy.sh
    on:
      repo: dashevo/insight-api
      tags: true
