dist: bionic
language: node_js

# Support Active LTS versions of Node.js
node_js:
  - '10'
  - '12'

addons:
  apt:
    update: true
    sources:
      - sourceline: 'deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled

branches:
  only:
    - master
    # Allow builds for version tags (e.g. v1.0.0)
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

before_install:
  - sudo apt-get -y install docker-ce
  # Login to NPM registry
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  # Use latest supported NPM in order to speedup build and support `npm ci`
  - npm i -g npm@6

install:
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  - docker buildx create --name xbuilder --use
  - npm ci

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/travis-deploy.sh
    on:
      repo: dashevo/insight-api
      tags: true
